---
output:
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 2
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../../man/figures/CCA_analysis-",
  out.width = "100%"
)
```

# `Glmnet` stability studies

## Prerequisites

```{r}
library(CovCoExpNets)
library(magrittr)
library(dplyr)

doParallel::registerDoParallel(13)
```

```{r}
brain_data.path <- "~/GTEx_data/"

data = readRDS(paste0(brain_data.path, "data.combined.rds"))
age = readRDS(paste0(brain_data.path, "age.combined.rds"))

m <- lapply(age, function(x) x$mean)
d <- lapply(age, function(x) x$standard.deviation)
age <- lapply(age, function(x) x$covariate)
```

```{r}
# Calculamos el CCA de todo un conjunto
estimateCCA_Heatplot <- function(genes.subset, method, name = NA){
  if(file.exists(paste0("heatplot_variables/", name))){
    heat_map = readRDS(paste0("heatplot_variables/", name))
  }else{
    heat_map = matrix(NA, nrow=length(genes.subset), ncol=length(genes.subset))
  }
  heat_plot = foreach(i = 1:length(genes.subset), .combine = "rbind") %:%
    foreach(j = 1:length(genes.subset), .combine = "cbind") %do% {
      if(i == j | j < i){
        return(NA)
      }else if(!is.na(heat_map[i, j])){
        logger::log_info(paste0("Found previous CCA for ", name, " row ", i, " column ", j, ": ", heat_map[i, j]))
        return(heat_map[i, j])
      }else{
        heat_map[i, j] = estimateCCA_pairwise(genes.subset, method, i, j)
        logger::log_info(paste0("For ", name, " row ", i, " column ", j, ": ", heat_map[i, j]))
        if(!is.na(name)){
          heat_map %>% saveRDS(paste0("heatplot_variables/", name))  
        }
        return(heat_map[i, j])
      }
    }
  return(heat_map)
}

getCommonGenes <- function(selected.genes, i, j){
  common.genes = intersect(selected.genes[[i]], selected.genes[[j]])
  common.genes
}

# Calculamos el CCA de unos tejidos concretos
estimateCCA_pairwise <- function(genes.subset, method, i, j){
  tryCatch({
    common.genes = getCommonGenes(genes.subset, i, j)
    if(dim(data[[i]])[2] < dim(data[[j]])[2]){
      data.a = data[[i]][common.genes, ] %>% as.matrix()
      data.b = data[[j]][common.genes, ] %>% as.matrix()
    }else{
      data.a = data[[j]][common.genes, ] %>% as.matrix()
      data.b = data[[i]][common.genes, ] %>% as.matrix()
    }
    
    if(method == "shrinkage"){
      results_shrink = mixOmics::rcc(data.a, data.b, method = "shrinkage")
      return(results_shrink$cor[1])
    }else if(method == "ridge"){
      cv = mixOmics::tune.rcc(data.a, data.b, validation = "Mfold", folds = 5, plot = FALSE)
      results_ridge = mixOmics::rcc(data.a, data.b, method = "ridge", lambda1 = cv$opt.lambda1, lambda2 = cv$opt.lambda2)
      return(results_ridge$cor[1])
    }else if(method == "rcc"){
      cv = CCA::estim.regul(data.a, data.b, plt = FALSE)
      results_rcc = CCA::rcc(data.a, data.b, lambda1 = cv$lambda1, lambda2 = cv$lambda2)
      return(results_rcc$cor[1])
    }else if(method == "cc"){
      results_cc = CCA::cc(data.a, data.b)
      return(results_cc$cor[1])
    }
  }, error=function(err) return(NA))
}

prepareDataPlot = function(data, selected.genes, diag = 1, upper = TRUE){
  r = foreach(i = 1:length(selected.genes)) %:% foreach(j = 1:length(selected.genes)) %do%{
    if (i == j){
      data[i, j] = diag
    }
    
    if(upper){
      data[j, i] = data[i, j]
    }else{
      data[i, j] = data[j, i]
    }
  }
  return(data)
}
```

```{r}
genes.freq = CovCoExpNets::geneFrequency(data, age, seed = 1796)
genes.subset <- reduceGenes(genes.freq, mrfa = 0.9)
cvfit = glmnetGenesSubset(data, age, genes.subset, train.split = 1)
genes.subset.covco = lapply(extractModelGenes(cvfit), "[", , "Genes")

genes.subset = genes.subset.covco
method = "shrinkage"
name = NA
heatplot.covco.shrinakge = estimateCCA_Heatplot(genes.subset.covco, "shrinkage")
```

```{r fig.width=10, fig.height=8.5}
selected.genes = genes.subset.covco
heatplot = heatplot.covco.shrinakge

heatplot = prepareDataPlot(heatplot, selected.genes)
colnames(heatplot) = names(selected.genes)
rownames(heatplot) = names(selected.genes)

heat_map = matrix(0, nrow=length(selected.genes), ncol=length(selected.genes))
r = foreach(i = 1:length(selected.genes)) %:%
  foreach(j = i:length(selected.genes)) %do% {
    common.genes = length(intersect(selected.genes[[i]], selected.genes[[j]]))
    heat_map[i, j] = common.genes/length(selected.genes[[i]])
    heat_map[j, i] = common.genes/length(selected.genes[[j]])
  };
perc.limit = 0.08
r = foreach(i = 1:length(selected.genes)) %:% foreach(j = i:length(selected.genes)) %do%{
  if(heat_map[i, j] <= perc.limit | heat_map[j, i] <= perc.limit){
    heat_map[i, j] <- NA
    heat_map[j, i] <- NA
  }
}
heat_map

heatplot[is.na(heat_map)] = NA
heatplot[is.na(heatplot)] = 0
row_dend = heatplot %>% dist() %>% hclust() %>% as.dendrogram()
#heatplot[heatplot == 0] = NA

test = heatplot %>% round(2)
diag(test) = "1"
test[is.na(test)] = "0"
pheatmap::pheatmap(
  heatplot,
  color = hcl.colors(50, "RdYlGn"),#[5:45],
  border_color = "black",
  angle_col = 45,
  display_numbers = test,
  number_format = "%s",
  fontsize_number = 11,
  number_color = "black",
  cluster_rows = as.hclust(row_dend %>% dendextend::ladderize(right = T)),
  cluster_cols = as.hclust(row_dend %>% dendextend::ladderize(right = T)),
  na_col = "white",
  width = 11,
  height = 8.5,
  fontsize = 12,
  #legend_breaks = c(0.85, 0.90, 0.95, 1),
  #labels_col = colnames(heatplot) %>% as.character(),
  cellheight = 28, cellwidth=32,
  filename = "CCA_plots/CCA_covco_8_colored.png",
)
```

